#! /usr/bin/env python


import sys
import os
import re
from datetime import datetime, date, time
import string
import math
import time
from operator import itemgetter

if len(sys.argv)!=2:
	print 'Usage: msleep time_in_millis'
 	exit();

millis_to_sleep=int(sys.argv[1])
seconds_to_sleep = float(millis_to_sleep) / 1000
time.sleep(seconds_to_sleep)