#! /usr/bin/env python

import sys
import corestats


if len(sys.argv) != 3:
    print 'Usage: slow_cutoff cutoff values'
    exit();

cutoff=int(sys.argv[1])
name=sys.argv[2]
vals = {}
print "cutoff=%d, values=%s" % (cutoff, name)

def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

infile = open(name,'r')
for line in infile:
    cols = line.split()
    index=0
    for col in cols:
        col = col.strip('%')
        try: vals[index].append(float(col))
        except KeyError: vals[index] = [float(col)]
        index += 1

stats = corestats.Stats(vals[0])
print "cutoff=%d, median=%f" % (cutoff, stats.median())
if stats.median() > cutoff:
    exit(0)
else :
    exit(-1)
